// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://crtxmoyjbwfrhkpnkeqp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNydHhtb3lqYndmcmhrcG5rZXFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5NDcxNDIsImV4cCI6MjA1NzUyMzE0Mn0.CeS0o1fYzU4X0i-4LtUre0vPUOTHStNI5tWYdoOjBJk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);